$ErrorActionPreference = "Stop"
Write-Host ""
Write-Host "AION ICLI installer"
Write-Host "Install preview complete."
Write-Host ""
Write-Host "Run AION with:"
Write-Host "  .\bin\aion.cmd `"Who are you, AION?`""
Write-Host ""
Write-Host "AION_ICLI_INSTALL_PREVIEW_OK"
